// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoryFlow_Database;

#nullable disable

namespace StoryFlow_Database.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260812224209_AddWordLessonImage")]
    partial class AddWordLessonImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoryFlow_Database.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaTitleContent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetaTitleDescription")
                        .IsRequired()
                        .HasMaxLength(115)
                        .HasColumnType("character varying(115)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("UrlText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.BlogPostSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogPostId")
                        .HasColumnType("integer");

                    b.Property<string>("H3Title")
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogPostSections");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoryId")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Sentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishMeaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PolishMeaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishDescription")
                        .HasColumnType("text");

                    b.Property<string>("EnglishStory")
                        .HasColumnType("text");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("text");

                    b.Property<int?>("LanguageLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfQuestions")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderInSeason")
                        .HasColumnType("integer");

                    b.Property<string>("PolishDescription")
                        .HasColumnType("text");

                    b.Property<string>("PolishStory")
                        .HasColumnType("text");

                    b.Property<string>("PolishTitle")
                        .HasColumnType("text");

                    b.Property<int?>("StoryCategory")
                        .HasColumnType("integer");

                    b.Property<int?>("StorySeasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("StorySize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorySeasonId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.StoryPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonusPointsForStoryLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("PointsPerAnswer")
                        .HasColumnType("integer");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoryId")
                        .IsUnique();

                    b.ToTable("StoryPoints");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.StorySeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisibleForUser")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PointsRequiredToUnlock")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StorySeazons");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PremiumAccountDays")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<int>("Tickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HobbyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHobbies");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SentenceId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SentenceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSentences");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestResult")
                        .HasColumnType("integer");

                    b.Property<bool>("HasReceivedStoryLengthBonus")
                        .HasColumnType("boolean");

                    b.Property<double>("PercentageScore")
                        .HasColumnType("double precision");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("UserStories");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishWord")
                        .HasColumnType("text");

                    b.Property<string>("PolishWord")
                        .HasColumnType("text");

                    b.Property<int>("WordLessonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WordLessonId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.WordLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int?>("OrderInSeason")
                        .HasColumnType("integer");

                    b.Property<string>("PolishTitlte")
                        .HasColumnType("text");

                    b.Property<int?>("StorySeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorySeasonId");

                    b.ToTable("WordLessons");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.WordPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("PointsPerWord")
                        .HasColumnType("integer");

                    b.Property<int>("WordLessonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WordLessonId")
                        .IsUnique();

                    b.ToTable("WordPoints");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Answer", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.BlogPostSection", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.BlogPost", "BlogPost")
                        .WithMany("Sections")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Question", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Quiz", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Story", "Story")
                        .WithOne("Quiz")
                        .HasForeignKey("StoryFlow_Database.Entities.Quiz", "StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Sentence", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Story", "Story")
                        .WithMany("Sentences")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Story", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.StorySeason", "StorySeason")
                        .WithMany("Stories")
                        .HasForeignKey("StorySeasonId");

                    b.Navigation("StorySeason");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.StoryPoint", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Story", "Story")
                        .WithOne("StoryPoint")
                        .HasForeignKey("StoryFlow_Database.Entities.StoryPoint", "StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.User", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserHobby", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Hobby", "Hobby")
                        .WithMany("UserHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryFlow_Database.Entities.User", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserSentence", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Sentence", "Sentence")
                        .WithMany("UserSavedSentences")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryFlow_Database.Entities.User", "User")
                        .WithMany("UserSentences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.UserStory", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.Story", "Story")
                        .WithMany("UserStories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryFlow_Database.Entities.User", "User")
                        .WithMany("UserStories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Word", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.WordLesson", "WordLesson")
                        .WithMany("Words")
                        .HasForeignKey("WordLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordLesson");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.WordLesson", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.StorySeason", "StorySeason")
                        .WithMany("WordLessons")
                        .HasForeignKey("StorySeasonId");

                    b.Navigation("StorySeason");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.WordPoint", b =>
                {
                    b.HasOne("StoryFlow_Database.Entities.WordLesson", "WordLesson")
                        .WithOne("WordPoint")
                        .HasForeignKey("StoryFlow_Database.Entities.WordPoint", "WordLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordLesson");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.BlogPost", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Hobby", b =>
                {
                    b.Navigation("UserHobbies");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Sentence", b =>
                {
                    b.Navigation("UserSavedSentences");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.Story", b =>
                {
                    b.Navigation("Quiz");

                    b.Navigation("Sentences");

                    b.Navigation("StoryPoint");

                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.StorySeason", b =>
                {
                    b.Navigation("Stories");

                    b.Navigation("WordLessons");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.User", b =>
                {
                    b.Navigation("UserHobbies");

                    b.Navigation("UserSentences");

                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("StoryFlow_Database.Entities.WordLesson", b =>
                {
                    b.Navigation("WordPoint");

                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
